apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-token-updater
  namespace: grafana
spec:
  schedule: "0 */1 * * *"  # 每小時執行一次
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: grafana-token-updater
          containers:
          - name: token-updater
            image: docker.io/juouyang/grafana-tools:1.0.0
            command:
            - /bin/sh
            - -c
            - |
              # 創建新的 token
              NEW_TOKEN="Bearer $(oc create token grafana-token-updater -n grafana)"
              oc whoami
          restartPolicy: Never
