---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-editor
  namespace: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-editor
  namespace: grafana
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: ["integreatly.org"]
  resources: ["grafanadatasources"]
  verbs: ["get", "update"]

- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: ["grafana.integreatly.org"]
  resources: ["grafanadatasources"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["grafana.integreatly.org"]
  resources: ["grafanadatasources"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-editor
  namespace: grafana
subjects:
- kind: ServiceAccount
  name: grafana-editor
roleRef:
  kind: Role
  name: grafana-editor
  apiGroup: rbac.authorization.k8s.io
